sudo: required
services: 
  - docker

before_install:
  - docker build -t davidhospodka/docker-react -f Dockerfile .

script:
  - docker run -e CI=true davidhospodka/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker-react2
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-289546914006"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"